export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const USER_INFO = 'USER_INFO';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const VERIFY_EMAIL_LOADING = 'VERIFY_EMAIL_LOADING';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_ERRORS = 'VERIFY_ERRORS';

// LOGOUT
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const VERIFY_LOADING = 'VERIFY_LOADING';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

export const SET_TIMEOUT_SHOW = 'SET_TIMEOUT_SHOW';

export const SET_ACTIVE_ROLE_SUCCESS = 'SET_ACTIVE_ROLE_SUCCESS';
export const SET_ACTIVE_ROLE_FAIL = 'SET_ACTIVE_ROLE_FAIL';
